### ISSUE TITLE
测试账号

### ISSUE THREAD

**Issue by MarcusXiaoFan** [LeeRayno/react-antd-mobile-demo#1]
能更新吗？

**Comment by LeeRayno** [comment]
你好，这个是公司用vue写的项目，估计账号只有公司内部能访问，我只是用部分功能来react练下手，并且是两个月前写的了，现在react升级到16了，router好像都不需要history了。并且antd-mobile也生成2.0了，配置什么的也已经变了。估计现在这个你来练手也不合适了。

发自我的 iPhone
